# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # config.vm.box = "ubuntu/trusty64"
  config.vm.box = "hashicorp/precise64"
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 8888, host: 8888

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.name = "my_vagrant_ubuntu"
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "1024"
    # vb.memory = "256" # if y
  end
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision :shell, path: 'loader.sh', privileged: false

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y python-dev
  #   sudo apt-get install -y python-pip
  #   sudo pip install --upgrade ipython[all]
  #   sudo mkdir /vagrant/notebook
  # SHELL

  # config.vm.provision "shell", run: "always", inline: <<-SHELL
  #   ipython notebook --notebook-dir=/vagrant/notebook --no-browser --ip=0.0.0.0 &
  # SHELL

end